"""Change embedding type to vector

Revision ID: c4fef20d3a62
Revises: edf2a52c4ecb
Create Date: 2026-02-17 18:28:29.043205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "c4fef20d3a62"
down_revision: Union[str, Sequence[str], None] = "edf2a52c4ecb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column(
        "places",
        sa.Column(
            "embedding_temp", pgvector.sqlalchemy.vector.VECTOR(dim=1536)
        ),
    )

    op.execute("UPDATE places SET embedding_temp = NULL")

    op.drop_column("places", "embedding")

    op.alter_column("places", "embedding_temp", new_column_name="embedding")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "places",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
