"""Add embedding column to places

Revision ID: edf2a52c4ecb
Revises: 0831b2d9d585
Create Date: 2026-02-17 17:35:08.715520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf2a52c4ecb'
down_revision: Union[str, Sequence[str], None] = '0831b2d9d585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('embedding', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'embedding')
    # ### end Alembic commands ###
